CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    BIRTHDAY TIMESTAMP,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(255),
    CPF VARCHAR(11),
    TYPE INTEGER
);